# Generated by Django 2.1 on 2018-09-04 05:53

from django.db import migrations, models
import django.db.models.deletion
import picker.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt_add', models.DateTimeField()),
                ('dt_update', models.DateTimeField(default=None)),
                ('enable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('verification', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt_add', models.DateTimeField()),
                ('dt_update', models.DateTimeField(default=None)),
                ('enable', models.BooleanField(default=True)),
                ('verification', models.BooleanField(default=False)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_in_pairs', related_query_name='base_in_pair', to='picker.Currency')),
                ('quoted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quoted_in_pairs', related_query_name='quoted_in_pair', to='picker.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt_add', models.DateTimeField()),
                ('dt_update', models.DateTimeField(default=None)),
                ('enable', models.BooleanField(default=True)),
                ('separator', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('fee', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeMarket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt_add', models.DateTimeField()),
                ('dt_update', models.DateTimeField(default=None)),
                ('enable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[(picker.models.MarketStatuses('verification'), 'verification'), (picker.models.MarketStatuses('pending'), 'pending'), (picker.models.MarketStatuses('maintenance'), 'maintenance'), (picker.models.MarketStatuses('active'), 'active')], default=picker.models.MarketStatuses('verification'), max_length=2)),
                ('currency_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picker.CurrencyPair')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picker.Exchange')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='exchangemarket',
            unique_together={('exchange', 'currency_pair')},
        ),
        migrations.AlterUniqueTogether(
            name='currencypair',
            unique_together={('base', 'quoted')},
        ),
    ]
